version: '3'
services:
  node:
    build:
      context: .
      dockerfile: .docker/node.dockerfile
    volumes:
        - ./:/app
        - /app/node_modules
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    build:
      context: .
      dockerfile: .docker/mongo.dockerfile
    ports:
      - "27017:27017"